### ISSUE TITLE
Provide ability to specify jscs options

### ISSUE THREAD

**Issue by ffesseler** [idok/jscs-plugin#5]
It's possible to use jscs on ES6 projects since 1.7.0 when activating the *esnext* flag.

Would be cool to have a text input to provide jscs options :)

**Comment by Coobaha** [comment]
+1

**Comment by idok** [comment]
Done, will be available in next version in a couple of days

**Comment by LeoYuan** [comment]
I'm using version 1.0.3, but I still not able to find where to specify option for jscs, could you tell me how to accomplish that?
![9ddc483a-81ce-4d61-87e6-25a5b66bd748](https://cloud.githubusercontent.com/assets/1195765/6773071/7625b97a-d146-11e4-9371-de1c591b2fda.png)

**Comment by LeoYuan** [comment]
I got it, just specify an option in .jscsrc would be fine.
```
{
  "esnext": true
}
```

**Comment by idok** [comment]
You are using the bundled plugin by jetbrains.
